# Generated by Django 3.2.9 on 2021-12-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findysport_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='local',
            name='ciudad',
            field=models.CharField(default='cadiz', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findysport_app.encargado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cod_postal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
