# Generated by Django 3.2.9 on 2022-01-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findysport_app', '0003_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
